### ISSUE TITLE
Configuring in HA UI forces lowercase

### ISSUE THREAD

**Issue by pathofleastresistor** [daviswieck/ha-college-football#2]
Im having an issue where configuring the integration in the UI will make "TEX" to "tex" and the team cannot be found. Putting "TEX" in the configuration.yaml file works fine.

**Comment by daviswieck** [comment]
I've got an upcoming fix for this. Just haven't had time to complete it yet. If figuring through the UI, back space all auto loaded teams, and capitalize TEX. Or it has in my testing.

**Comment by daviswieck** [comment]
Should be fixed now... 

https://github.com/daviswieck/ha-college-football/releases/tag/V.7
