### ISSUE TITLE
Bye week for Longhorns

### ISSUE THREAD

**Issue by pathofleastresistor** [daviswieck/ha-college-football#5]
The Texas Longhorns have a bye week this week, but the sensor is reporting NOT_FOUND.

**Comment by pathofleastresistor** [comment]
I don't see teamsOnBye in the API response

https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard?groups=04

**Comment by daviswieck** [comment]
It will report that because they will not show up in the api at all this week. 
It will return to normal next week

**Comment by daviswieck** [comment]
I will update readme to reflect
